### ISSUE TITLE
bad url 

### ISSUE THREAD

**Issue by bulfinch** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#46]
Not sure if you provide support for this script... 

I can get the script to work on a Windows machine, but not on a Linux machine with PowerShell docker. 

Running this command 
`sudo docker run --rm -it -v "/volume1/docker/upgradinatorr:/upgradinatorr" mcr.microsoft.com/powershell:latest pwsh /upgradinatorr/Upgradinatorr/upgradinatorr.ps1 -apps radarr-4k,radarr,sonarr -verbose`

`Exception: Your URL for Radarr-4k,Radarr,Sonarr is not formatted correctly, it should start with http(s):// and not end in /`

this is my config
[General]
discordWebhook=https://discordapp.com/api/webhooks/[redacted]

[Radarr-4k]
radarrApiKey=[redacted]
radarrCount=0
radarrMonitored=true
radarrMovieStatus=released
radarrTagName=upgradinatorr
radarrUnattended=false
radarrUrl=http://192.168.1.100:17878

[Radarr]
radarrApiKey=[redacted]
radarrCount=1
radarrMonitored=true
radarrMovieStatus=released
radarrTagName=upgradinatorr
radarrUnattended=false
radarrUrl=http://192.168.1.100:7878

[Sonarr]
sonarrApiKey=[redacted]
sonarrCount=0
sonarrMonitored=true
sonarrSeriesStatus=
sonarrTagName=upgradinatorr
sonarrUnattended=false
sonarrUrl=http://192.168.1.100:8989

**Comment by FonduemangVI** [comment]
Hey @bulfinch take a look at the latest config example the config parameters have been updated. I ran into the same issue last night

They look like this now
[Radarr]
ApiKey=
Count=10
Monitored=true
MovieStatus=released
TagName=
Unattended=false
Url=

**Comment by phishyphun** [comment]
Hello,

I'm actually getting the same error for radarr and radarr-4k:

`Your URL for Radarr,Radarr-4K is not formatted correctly, it should start with http(s):// and not end in /`

My conf is using the latest example:

[General]
discordWebhook=https://discord.com/api/webhooks/[redacted]

[Radarr]
ApiKey=[redacted]
Count=10
Monitored=true
MovieStatus=released
TagName=
Unattended=false
Url=http://192.168.1.122:7878

[Radarr4K]
ApiKey=[redacted]
Count=10
Monitored=true
MovieStatus=released
TagName=
Unattended=false
Url=http://192.168.1.122:7879

**Comment by FonduemangVI** [comment]
@phishyphun are your powershell files updated to the latest version as well?

**Comment by phishyphun** [comment]
> @phishyphun are your powershell files updated to the latest version as well?

Yes. I'm using the latest Powershell 7 version from MS.

**Comment by FonduemangVI** [comment]
Ah sorry I mean the latest ps1 and psm1 file from GH

**Comment by phishyphun** [comment]
> Ah sorry I mean the latest ps1 and psm1 file from GH

Yes went ahead and cloned again to be sure.

```
PS C:\Program Files\PowerShell\7> git clone "https://github.com/angrycuban13/Scripts.git" "C:\linux\"
Cloning into 'C:\linux'...
remote: Enumerating objects: 461, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 461 (delta 104), reused 126 (delta 70), pack-reused 272
Receiving objects: 100% (461/461), 119.89 KiB | 8.56 MiB/s, done.
Resolving deltas: 100% (237/237), done.
PS C:\Program Files\PowerShell\7> pwsh C:\linux\Upgradinatorr\upgradinatorr.ps1 -apps radarr,radarr-4k -verbose
VERBOSE: Loading module from path 'C:\linux\Upgradinatorr\upgradinatorr.psm1'.
VERBOSE: Exporting function 'Add-Tag'.
VERBOSE: Exporting function 'Confirm-AppConnectivity'.
VERBOSE: Exporting function 'Confirm-AppURL'.
VERBOSE: Exporting function 'Get-TagId'.
VERBOSE: Exporting function 'Read-IniFile'.
VERBOSE: Exporting function 'Remove-Tag'.
VERBOSE: Exporting function 'Search-Movies'.
VERBOSE: Exporting function 'Search-Series'.
VERBOSE: Exporting function 'Send-DiscordWebhook'.
VERBOSE: Importing function 'Add-Tag'.
VERBOSE: Importing function 'Confirm-AppConnectivity'.
VERBOSE: Importing function 'Confirm-AppURL'.
VERBOSE: Importing function 'Get-TagId'.
VERBOSE: Importing function 'Read-IniFile'.
VERBOSE: Importing function 'Remove-Tag'.
VERBOSE: Importing function 'Search-Movies'.
VERBOSE: Importing function 'Search-Series'.
VERBOSE: Importing function 'Send-DiscordWebhook'.
VERBOSE: Location for config file is C:\linux\Upgradinatorr\upgradinatorr.conf
VERBOSE: Parsing config file
VERBOSE: Config file parsed successfully
Exception: Your URL for Radarr,Radarr-4K is not formatted correctly, it should start with http(s):// and not end in /
```

**Comment by bulfinch** [comment]
Ok, I got it to work. 

I went into the DEV branch and copied the code from within, `upgradinator.ps1` opened the corresponding file on my NAS and pasted in the updated code. 

All this because I don't know how to pull the dev branch using `git clone "https://github.com/angrycuban13/Scripts.git" "/volume1/docker/upgradinatorr"`

**Comment by bulfinch** [comment]
ah. so returning to the `latest` `.ps1` still produces the error. Appreciate your time.

**Comment by angrycuban13** [comment]
I can't seem to replicate your issue. Can you paste your config file on a gist and remove any sensitive data? I even threw the URLs you provided for your config through a regex check and it seems correct

![Example Config](https://sharex.angrycuban.xyz/haRe3/xOwOGIyE88.png/raw)

![Logic Check](https://sharex.angrycuban.xyz/haRe3/LeHAvehO68.png/raw)

![Linux Powershell](https://sharex.angrycuban.xyz/haRe3/XeqASAwu30.png/raw)

![Container](https://sharex.angrycuban.xyz/haRe3/PUNeSeCu02.png/raw)

![Regex](https://sharex.angrycuban.xyz/haRe3/YepAMUda57.png)

**Comment by bulfinch** [comment]
Before posting this, I deleted and redownloaded the git to make sure I hadn't done something funky and no change with this config.

https://gist.github.com/bulfinch/540bd56c1c52d05c27adb27dbe5d7ab1

**Comment by bulfinch** [comment]
https://gist.github.com/bulfinch/540bd56c1c52d05c27adb27dbe5d7ab1

**Comment by bulfinch** [comment]
I think it must be the version of linux docker powershell I'm using for this as the exact same config works on windows. I've tried the `latest` and `preview` versions and still same result `latest` is version `7.2` `preview` is `7.3`

**Comment by phishyphun** [comment]
> I think it must be the version of linux docker powershell I'm using for this as the exact same config works on windows. I've tried the `latest` and `preview` versions and still same result `latest` is version `7.2` `preview` is `7.3`

Well, I'm trying the same thing and getting the same error on my Windows machine using Powershell.

**Comment by angrycuban13** [comment]
I was going to say that it sounds like some funky Linux stuff but I'll see if I can help you figure it out

**Comment by phishyphun** [comment]
Here's mine:

<script src="https://gist.github.com/phishyphun/d7731c8188a8a450187228f4eac68b95.js"></script>

**Comment by angrycuban13** [comment]
There's honestly not much to the function. Try to run it standalone and see if you get the same error

* Open Powershell
* Copy/paste code below
* Create a new variable and assign it the same URL `$url=http://192.168.1.122:7878`
* `Confirm-AppURL -url $url`
* Does it still error?

```powershell
function Confirm-AppURL {
    [CmdletBinding()]
    param (
        $app,
        $url
    )

    if ($url -notmatch "https?:\/\/" -or $url.EndsWith("/")){
        throw "Your URL for $((Get-Culture).TextInfo.ToTitleCase($app)) is not formatted correctly, it should start with http(s):// and not end in /"
    }
    else {
        Write-Verbose "$((Get-Culture).TextInfo.ToTitleCase("$app")) URL confirmed"
    }
}
```
I'm updating to the latest PowerShell on my computer and will test, maybe something got screwed up in the latest release.

**Comment by angrycuban13** [comment]
How are you running this on Windows that you are getting an error?

**Comment by phishyphun** [comment]
![image](https://user-images.githubusercontent.com/73494231/198903695-04651a5a-f0cb-4e3e-ba50-8a063cbba45d.png)

**Comment by angrycuban13** [comment]
Ah, I see the issue. Stupid splatting - I'm sorry the `dev` branch is actually usable, so please switch to that as it is fixed on there

**Comment by angrycuban13** [comment]
Fixed by merging 2787674df812497358c78f1cdd059b6265defb58

**Comment by phishyphun** [comment]
Thanks. Seemed to fix it for radarr instance. However, I'm still getting this for radarr-4k:

![image](https://user-images.githubusercontent.com/73494231/198904480-e14f1a2f-57fd-4cab-ab14-944916b952d8.png)

**Comment by phishyphun** [comment]
And again, my conf:

[General]
discordWebhook=https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxx

[Radarr]
ApiKey=xxxxxxxxxxxxxxxx
Count=10
Monitored=true
MovieStatus=released
TagName=upgradinatorr
Unattended=false
Url=http://100.64.101.74:7878

[Radarr4K]
ApiKey=yyyyyyyyyyyyyyyyyyy
Count=10
Monitored=true
MovieStatus=released
TagName=upgradinatorr
Unattended=false
Url=http://100.64.101.74:7878

**Comment by angrycuban13** [comment]
You are passing `radarr-4k` as an app instead of `radarr4K`.

**Comment by phishyphun** [comment]
Good call. We're all good to go now. I appreciate all the help!

**Comment by bulfinch** [comment]
Hey works for me too. Thank you much.
